import fs from 'node:fs/promises';
import path from 'node:path';
import matter from 'gray-matter';
import type { BuiltPage, SourceEntry } from './types';

const root = process.cwd();

async function walk(dir: string, match: (file: string) => boolean): Promise<string[]> {
  let out: string[] = [];
  let items: import('node:fs').Dirent[];
  try {
    items = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return [];
  }
  for (const item of items) {
    const full = path.join(dir, item.name);
    if (item.isDirectory()) out = out.concat(await walk(full, match));
    else if (match(full)) out.push(full);
  }
  return out;
}

/** Line number of each top-level frontmatter key, so violations can point at it. */
function frontmatterLines(raw: string): Record<string, number> {
  const lines = raw.split('\n');
  const out: Record<string, number> = {};
  if (lines[0]?.trim() !== '---') return out;
  for (let i = 1; i < lines.length; i += 1) {
    if (lines[i]?.trim() === '---') break;
    const key = /^([A-Za-z_][\w-]*):/.exec(lines[i] ?? '');
    if (key) out[key[1]!] = i + 1;
  }
  return out;
}

/**
 * Content files under content/.
 *
 * Drafts are excluded by default. A draft never produces a page, so the rules
 * that define "publishable" cannot apply to it — letting them apply would mean
 * an unfinished file in the repository blocks the whole site from deploying.
 * Pass `includeDrafts` when you need the raw set, e.g. to report how many were
 * held back.
 */
export async function collectEntries(options: { includeDrafts?: boolean } = {}): Promise<SourceEntry[]> {
  const contentRoot = path.join(root, 'content');
  const files = await walk(contentRoot, (file) => file.endsWith('.md') || file.endsWith('.mdx'));

  const entries = await Promise.all(
    files.sort().map(async (file) => {
      const raw = await fs.readFile(file, 'utf8');
      const parsed = matter(raw);
      const rel = path.relative(root, file);
      const type = path.relative(contentRoot, file).split(path.sep)[0] ?? 'unknown';
      return {
        file: rel,
        type,
        data: parsed.data as Record<string, any>,
        body: parsed.content,
        frontmatterLines: frontmatterLines(raw),
      };
    }),
  );

  return options.includeDrafts ? entries : entries.filter((entry) => entry.data.draft !== true);
}

export async function collectPages(): Promise<BuiltPage[]> {
  const distRoot = path.join(root, 'dist');
  const files = await walk(distRoot, (file) => file.endsWith('.html'));

  return Promise.all(
    files.sort().map(async (file) => {
      const html = await fs.readFile(file, 'utf8');
      const rel = path.relative(distRoot, file);
      const url = `/${rel.replace(/index\.html$/, '').replace(/\\/g, '/')}`;
      return { url, file: path.relative(root, file), html };
    }),
  );
}

export async function hasBuild() {
  try {
    await fs.access(path.join(root, 'dist'));
    return true;
  } catch {
    return false;
  }
}

/**
 * What the last build was: where the engine was mounted, and which fixed pages
 * it published.
 *
 * The gate runs in its own process and never loads astro.config, so it cannot
 * see `engine({ mount })`. The build writes it down instead — `.aifb/build.json`,
 * next to dist/ and generated by the same run. `AIFB_MOUNT` overrides it for
 * anyone driving the rules directly.
 *
 * Missing file means the default, an engine at the origin root: that is what
 * every site had before the option existed, and a site that has not built yet
 * has no URL-shaped rules to run anyway.
 */
export async function readBuildInfo(): Promise<{ mount: string; pages: string[] }> {
  const fallback = { mount: process.env.AIFB_MOUNT?.replace(/\/+$/, '') ?? '', pages: [] as string[] };
  try {
    const raw = JSON.parse(await fs.readFile(path.join(root, '.aifb/build.json'), 'utf8'));
    return {
      mount: typeof raw.mount === 'string' ? raw.mount.replace(/\/+$/, '') : fallback.mount,
      pages: Array.isArray(raw.pages) ? raw.pages : [],
    };
  } catch {
    return fallback;
  }
}
