/**
 * Cloudflare Pages deploy artefacts, emitted at the end of the build.
 *
 * Two files that a static host reads and a static site cannot express on its
 * own — and both of which were missing:
 *
 * **`_redirects`** — the URL history of the site. Without it a migration is a
 * link-loss event: `pnpm migrate:ghost` renames slugs, every inbound link to an
 * old URL 404s, and nothing in the pipeline notices because the new pages are
 * all perfectly valid. The mapping is site data, so it lives in
 * `site/redirects.yaml`; migration appends to it rather than owning it.
 *
 * **`_headers`** — cache policy. Astro fingerprints everything under `/_astro/`,
 * so those files are safe to cache forever; HTML is not, and must revalidate or
 * a deploy takes hours to reach readers. The default (no header file at all)
 * gets one of those two wrong whichever way the host guesses.
 *
 * Redirect targets are checked against the pages actually built. A redirect
 * pointing at a page that no longer exists is worse than no redirect: it turns
 * one dead link into two hops ending in a 404.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';
import type { AstroIntegration } from 'astro';

type RedirectRule = { from: string; to: string; status?: number; note?: string };

const HEADERS = `# Generated by the engine at build time. Edit engine/deploy/cloudflare.ts.

# Astro fingerprints these filenames, so the content can never change under a
# given URL. Cache them for a year and never revalidate.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# Images and fonts shipped from public/ are not fingerprinted. A day is long
# enough to help, short enough that replacing one is not a week-long rollout.
/*.png
  Cache-Control: public, max-age=86400
/*.jpg
  Cache-Control: public, max-age=86400
/*.webp
  Cache-Control: public, max-age=86400
/*.svg
  Cache-Control: public, max-age=86400

# HTML must revalidate, or a deploy reaches readers whenever their cache feels
# like it. These pages are cheap; correctness is worth the round trip.
/*
  Cache-Control: public, max-age=0, must-revalidate
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
`;

function normalise(url: string) {
  if (/^https?:\/\//.test(url)) return url;
  const clean = url.split('#')[0]!.split('?')[0]!;
  const withSlash = clean.startsWith('/') ? clean : `/${clean}`;
  return withSlash.endsWith('/') || /\.[a-z0-9]{2,5}$/i.test(withSlash) ? withSlash : `${withSlash}/`;
}

export function cloudflarePages(): AstroIntegration {
  return {
    name: 'aifb:cloudflare-pages',
    hooks: {
      'astro:build:done': async ({ dir, pages, logger }) => {
        const outDir = fileURLToPath(dir);
        const root = process.cwd();

        /* ---- redirects ------------------------------------------------ */
        let rules: RedirectRule[] = [];
        try {
          const raw = await fs.readFile(path.join(root, 'site/redirects.yaml'), 'utf8');
          rules = (parse(raw)?.redirects ?? []) as RedirectRule[];
        } catch {
          // No redirects file is a normal state for a site with no URL history.
        }

        if (rules.length > 0) {
          // `pages` is every route the build produced, without leading slashes.
          const built = new Set(pages.map((page) => normalise(`/${page.pathname}`)));
          const problems: string[] = [];

          for (const [index, rule] of rules.entries()) {
            if (typeof rule?.from !== 'string' || typeof rule?.to !== 'string') {
              problems.push(`redirects[${index}] needs both "from" and "to".`);
              continue;
            }
            const to = normalise(rule.to);
            if (to.startsWith('http')) continue;
            if (!built.has(to)) {
              problems.push(
                `redirects[${index}] sends ${rule.from} to ${rule.to}, which this build does not produce. ` +
                  'A redirect to a 404 turns one dead link into two hops.',
              );
            }
          }

          if (problems.length > 0) {
            throw new Error(`Invalid site/redirects.yaml:\n- ${problems.join('\n- ')}`);
          }

          const body = [
            '# Generated from site/redirects.yaml at build time. Do not edit here.',
            ...rules.map((rule) => {
              const line = `${normalise(rule.from)}  ${normalise(rule.to)}  ${rule.status ?? 301}`;
              return rule.note ? `# ${rule.note}\n${line}` : line;
            }),
            '',
          ].join('\n');

          await fs.writeFile(path.join(outDir, '_redirects'), body);
          logger.info(`_redirects written (${rules.length} rule(s))`);
        }

        /* ---- headers -------------------------------------------------- */
        await fs.writeFile(path.join(outDir, '_headers'), HEADERS);
        logger.info('_headers written');
      },
    },
  };
}
