import { promises as fs } from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { parse } from 'yaml';

export type Redirect = {
  from: string;
  to: string;
  status: 301 | 302 | 303 | 307 | 308;
};

export type RedirectValidationResult = {
  redirects: Redirect[];
  errors: string[];
};

const outputHeader = '# Generated by pnpm redirects:generate. Do not edit.\n';
const allowedStatuses = new Set([301, 302, 303, 307, 308]);

async function walk(directory: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(directory, { withFileTypes: true });
    const nested = await Promise.all(entries.map((entry) => {
      const target = path.join(directory, entry.name);
      return entry.isDirectory() ? walk(target) : [target];
    }));
    return nested.flat();
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw error;
  }
}

function normalizeRoute(value: unknown, label: string, errors: string[]) {
  if (typeof value !== 'string' || !value.startsWith('/') || value.startsWith('//') || /[?#\s]/.test(value)) {
    errors.push(`${label}: route must be a root-relative path without spaces, query, or fragment`);
    return undefined;
  }
  if (value.includes('*') || value.includes(':')) {
    errors.push(`${label}: dynamic redirects are not supported because they cannot be checked for loops and chains`);
    return undefined;
  }
  const normalized = path.posix.normalize(value);
  if (normalized !== value || normalized.includes('..')) {
    errors.push(`${label}: route must be normalized`);
    return undefined;
  }
  return value === '/' || path.posix.extname(value) ? value : `${value.replace(/\/$/, '')}/`;
}

function contentRoute(collection: string, slug: string) {
  const route = collection === 'posts' ? 'writing' : collection;
  return `/${route}/${slug.replace(/^\/+|\/+$/g, '')}/`;
}

function legacyRoute(collection: string, legacySlug: string) {
  if (legacySlug.startsWith('/')) return legacySlug;
  return contentRoute(collection, legacySlug);
}

async function redirectsFromContent(root: string, errors: string[]) {
  const contentRoot = path.join(root, 'src/content');
  const files = (await walk(contentRoot)).filter((file) => /\.(?:md|mdx)$/.test(file));
  const redirects: Redirect[] = [];
  for (const file of files) {
    const relative = path.relative(contentRoot, file).split(path.sep).join('/');
    const collection = relative.split('/')[0];
    const { data } = matter(await fs.readFile(file, 'utf8'));
    if (!data.legacySlug) continue;
    if (typeof data.slug !== 'string' || typeof data.legacySlug !== 'string') {
      errors.push(`src/content/${relative}: legacySlug requires string slug and legacySlug values`);
      continue;
    }
    redirects.push({
      from: legacyRoute(collection, data.legacySlug),
      to: typeof data.canonical === 'string' ? data.canonical : contentRoute(collection, data.slug),
      status: 301,
    });
  }
  return redirects;
}

export async function collectRedirects(root = process.cwd()): Promise<RedirectValidationResult> {
  const errors: string[] = [];
  let document: unknown;
  try {
    document = parse(await fs.readFile(path.join(root, 'content-plans/redirects.yaml'), 'utf8'));
  } catch (error) {
    return { redirects: [], errors: [`content-plans/redirects.yaml: ${(error as Error).message}`] };
  }
  if (typeof document !== 'object' || document === null || Array.isArray(document)) {
    return { redirects: [], errors: ['content-plans/redirects.yaml: expected an object'] };
  }
  const config = document as { schemaVersion?: unknown; redirects?: unknown };
  if (config.schemaVersion !== 1 || !Array.isArray(config.redirects)) {
    return { redirects: [], errors: ['content-plans/redirects.yaml: expected schemaVersion 1 and a redirects array'] };
  }

  const rawRedirects = [...config.redirects, ...(await redirectsFromContent(root, errors))];
  const redirects: Redirect[] = [];
  for (const [index, raw] of rawRedirects.entries()) {
    const label = `redirects[${index}]`;
    if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
      errors.push(`${label}: expected an object`);
      continue;
    }
    const candidate = raw as { from?: unknown; to?: unknown; status?: unknown };
    const from = normalizeRoute(candidate.from, `${label}.from`, errors);
    const to = normalizeRoute(candidate.to, `${label}.to`, errors);
    const status = candidate.status ?? 301;
    if (!allowedStatuses.has(status as number)) errors.push(`${label}.status: expected 301, 302, 303, 307, or 308`);
    if (from && to && allowedStatuses.has(status as number)) redirects.push({ from, to, status: status as Redirect['status'] });
  }

  const bySource = new Map<string, Redirect>();
  for (const redirect of redirects) {
    if (redirect.from === redirect.to) errors.push(`${redirect.from}: redirect points to itself`);
    if (bySource.has(redirect.from)) errors.push(`${redirect.from}: duplicate redirect source`);
    else bySource.set(redirect.from, redirect);
  }
  for (const redirect of redirects) {
    const next = bySource.get(redirect.to);
    if (next) errors.push(`${redirect.from}: redirect chain detected through ${redirect.to}`);
  }

  const visiting = new Set<string>();
  const visited = new Set<string>();
  function visit(source: string, trail: string[]) {
    if (visiting.has(source)) {
      const loopStart = trail.indexOf(source);
      errors.push(`redirect loop detected: ${[...trail.slice(loopStart), source].join(' -> ')}`);
      return;
    }
    if (visited.has(source)) return;
    visiting.add(source);
    const target = bySource.get(source)?.to;
    if (target && bySource.has(target)) visit(target, [...trail, source]);
    visiting.delete(source);
    visited.add(source);
  }
  for (const source of bySource.keys()) visit(source, []);

  redirects.sort((left, right) => left.from.localeCompare(right.from));
  if (redirects.length > 2000) errors.push(`redirects: Cloudflare Pages allows at most 2,000 static redirects, found ${redirects.length}`);
  return { redirects, errors: [...new Set(errors)] };
}

export function renderRedirects(redirects: Redirect[]) {
  return `${outputHeader}${redirects.map((redirect) => `${redirect.from} ${redirect.to} ${redirect.status}`).join('\n')}${redirects.length ? '\n' : ''}`;
}

export async function generateRedirects(root = process.cwd()) {
  const result = await collectRedirects(root);
  if (result.errors.length > 0) throw new Error(result.errors.join('\n'));
  const output = renderRedirects(result.redirects);
  await fs.writeFile(path.join(root, 'public/_redirects'), output);
  return result.redirects;
}

export async function validateRedirects(root = process.cwd()) {
  const result = await collectRedirects(root);
  if (result.errors.length > 0) return result;
  const expected = renderRedirects(result.redirects);
  try {
    const actual = await fs.readFile(path.join(root, 'public/_redirects'), 'utf8');
    if (actual !== expected) result.errors.push('public/_redirects is stale; run pnpm redirects:generate');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') result.errors.push('public/_redirects is missing; run pnpm redirects:generate');
    else throw error;
  }
  return result;
}
