import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { stringify } from 'yaml';
import { collectRedirects, generateRedirects, validateRedirects } from './lib/redirects';

async function fixture() {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'afb-redirects-'));
  await fs.mkdir(path.join(root, 'content-plans'), { recursive: true });
  await fs.mkdir(path.join(root, 'src/content/posts'), { recursive: true });
  await fs.mkdir(path.join(root, 'public'), { recursive: true });
  return root;
}

const emptyRoot = await fixture();
await fs.writeFile(path.join(emptyRoot, 'content-plans/redirects.yaml'), stringify({ schemaVersion: 1, redirects: [] }));
assert.deepEqual(await generateRedirects(emptyRoot), []);
assert.equal(await fs.readFile(path.join(emptyRoot, 'public/_redirects'), 'utf8'), '# Generated by pnpm redirects:generate. Do not edit.\n');
assert.deepEqual((await validateRedirects(emptyRoot)).errors, []);
await fs.rm(emptyRoot, { recursive: true, force: true });

const validRoot = await fixture();
await fs.writeFile(path.join(validRoot, 'content-plans/redirects.yaml'), stringify({
  schemaVersion: 1,
  redirects: [{ from: '/old-about', to: '/about', status: 303 }],
}));
await fs.writeFile(path.join(validRoot, 'src/content/posts/new-article.mdx'), `---
title: New article
slug: new-article
legacySlug: old-article
---
`);
const generated = await generateRedirects(validRoot);
assert.deepEqual(generated, [
  { from: '/old-about/', to: '/about/', status: 303 },
  { from: '/writing/old-article/', to: '/writing/new-article/', status: 301 },
]);
const output = await fs.readFile(path.join(validRoot, 'public/_redirects'), 'utf8');
assert.ok(output.includes('/writing/old-article/ /writing/new-article/ 301'));
await fs.appendFile(path.join(validRoot, 'public/_redirects'), '# manual change\n');
assert.ok((await validateRedirects(validRoot)).errors.some((error) => error.includes('is stale')));
await fs.rm(validRoot, { recursive: true, force: true });

const invalidRoot = await fixture();
await fs.writeFile(path.join(invalidRoot, 'content-plans/redirects.yaml'), stringify({
  schemaVersion: 1,
  redirects: [
    { from: '/a/', to: '/b/', status: 301 },
    { from: '/b/', to: '/c/', status: 301 },
    { from: '/c/', to: '/a/', status: 301 },
    { from: '/a/', to: '/different/', status: 302 },
  ],
}));
const invalid = await collectRedirects(invalidRoot);
for (const expected of ['duplicate redirect source', 'redirect chain detected', 'redirect loop detected']) {
  assert.ok(invalid.errors.some((error) => error.includes(expected)), `Missing redirect error: ${expected}`);
}
await fs.rm(invalidRoot, { recursive: true, force: true });
console.log('Redirect pipeline tests passed.');
